# Site settings
title: Uptown Vocal
email: uptownvocal@columbia.edu
description: "Columbia University's Premier Jazz A Cappella Group!"
baseurl: ""
url: "http://www.uptownvocal.com"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"