# Site settings
title: Uptown Vocal
email: uptownvocal@columbia.edu
description: "Founded in 1991, Uptown Vocal is Columbia University's Premier Jazz Acappella Group"
baseurl: ""
url: "http://uptownvocal.com"
imgurl: "/assets/img"
memburl: "/assets/img/members"
jsurl: "/assets/js"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"